# Require the sign off of the privacy act page before some actions
show_privacy_act_page: true

# When false, always paper submission. When true -- EML310 post result decides.
# Serves as a handy emergency off switch in situations where the DMV back-end
# integration is not working right.
EnableDigitalService: true
EnablePaperService: false


###################
## Config Guide 6.1
## Configuration keys that toggle the user-visible behavior of 
## the eligibility dialog
##

eligibility:
  ### This config item turns on the VA-specific eligibility requirements. 
  ### When true, the remaining eligibility configuration has no effect
  enable_method_virginia: false
  # enable_method_STATE_NAME: Potentail future functionality
  
  ### When using the default eligibility requirements (i.e. no state-specific eligibility
  ### method is set to `true` above), the following `requirements` config item
  ### specifies a list of eligibility keys. Each of these keys will result in presenting the
  ### user with an interface to confirm that specific eligibility requirement. Each key 
  ### corresponds to a localization item under the eligibility.requirements namespace.
  ### If the given key is a string, the user will be presented with a checkbox with
  ### the string as a lable. If the user checks the box, they are agreeing that they
  ### meet the stated requirement. By default the box will not be checked.
  ### If the given key is a hash of further keys, the following
  ### structure of localiation keys will be assumed:
  ###     eligibility:
  ###       requirements:
  ###         complex_requirement:
  ###           question: "Do you meet this requirement?"
  ###           agree: "I meet the complex requirement"
  ###           disagree: "I do not meet the complex requirement"
  ###           ineligible: "You must meet this complex requirement to vote"
  ### When this structure is provided, the user will be present with the text specified by
  ### `question` followed by a radio button for each of the `agree` and `disagree` statement
  ### If the user selects the radio button corresponding to the `agree` statement,
  ### they will be able to vote. If they select the radio button corresponding to the
  ### `disagree` option, they will be shown the statement specified by `ineligible` if present.
  ### The `ineligible` key is optional.
  requirements:
    - all_requirements
  
  
  # When precheck is false, does not lookup user data based on IDs (and therefore does not check for eligibility)
  PreCheckForPaperless: false # was enable_dmvid_lookup
  SingleStatement: true # Skip all the other eligibilty checks and ask a single question to attest user's eligibility
  Age18: false # Show age checkbox on eligibility screen (if not shown, the age eligibility attribue defaults to TRUE)
  CombineWithIdentity: true #Show eligibility and identity in one page, usually when there are few eligibility questions
  CollectPersonalData: true #actually force to false when ComineWithIdentity is true
  
  
# When FALSE, showing the explanation page to ineligible
allow_ineligible_to_complete_form: false  

# When true we don't ask a top-level rights question on the eligibility page
enable_expanded_felony_mental_eligibility: true

# TRUE to place SSN / DMVID / DOB on eligibility page, FALSE -- on identity
personal_data_on_eligibility_page: true

# Require SSN field to be present on eligibility screen (both registration and update)
#   true = users who don't provide SSN are treated as ineligible
#   false = users who don't provide SSN are allowed to continue to register
ssn_required: false

# Length of DMV ID field
state_id_length:
  min: 9
  max: 12

# When false, DMV ID entry field is optional
# TBD: require_dmv_id: true
require_dmv_id: true


# Enable/disable the pre-population of residence address fields from DMV address, if available
enable_dmv_address_display: true

Identity:
  IncludeProtectedVoterBlock: false


# Enable/disable the needs-assitance option
enable_need_assistance_option: true

# Enable/disable the volunteer option
enable_volunteer_option: true

# Enable/disable the presentation of absentee options 
# to user in the domestic workflow for new registrations 
enable_absentee_option_domestic_new: false

# Enable/disable the presentation of absentee options
# to user in the domestic workflow for update existing registrations 
enable_absentee_option_domestic_update: false


################
## Configuration keys that toggle the user-visible behavior of 
## the page that displays voter info for user confirmation
## before proceeding to conclusion of the session
##

# When TRUE "edit" links are placed on the far right in the confirmation table
confirmation_table_right_justify: false

# Width of the labels column on confirm page (in px)
confirmation_table_labels_width: 224

# Show voting status on confirmation page
enable_confirm_voting_status_display: false





################
## Configuration keys that toggle the user-visible behavior of 
## the page that displays the oath
## at the conclusion of the session

# Shows / hides the assistant details section on oath page
# separate toggles for paperless OVR vs. requires PDF

Completion:
  IncludeAttestation: true
  CombineAttestationWithConfirmation: true
  Assistance:
    Paperless: false
    Paper: false



