en:
  title: Voter Registration - Rhode Island Department of State
  header_title: |
    <span class='title-sub'><a href="/">Rhode Island Department of State</a></span>
    <span class='title'><a href="http://sos.ri.gov/about-us">Nellie M. Gorbea</a></span>
    <span class='title-sub'>Secretary of state</span>
    