es:
  front:
    welcome:
      title: El registro de votantes
      text: ''        

    options:
      am_registered:
        title: "Am I Registered"
        subtitle: Check Your Registration Record
        text: Identify yourself to do a lookup in the voter register.
        button: Lookup Now
      add_to_register:
        title: "Register to vote"
        subtitle: Rhode Island Resident Voter
        text: Fill out an online form and provide a photo of your documentation.
        button: Start the Online Form
      add_to_intl_register:
        title: "<br/>Add Yourself to the International Register"
        subtitle: US Forces Members and Living Abroad
        text: Fill out an online form and provide a photo of your documentation.
        button: Start the Online Military/Overseas Form
      removal_from_register:
        title: "<br/>Removal From the Register"
        subtitle: All Registered R.I. Voters
        text: Identify yourself to do a lookup in the Register, and provide your updated information.
        button: Start the Online Update
      update_information:
        title: "<br/>Update Your Information on the Register"
        subtitle: All Registered R.I. Voters
        text: Identify yourself or a deceased elector, and complete the online form.    
        button: Update Now
           
    deadline: ""

