en:
  residence_address: Residence Address

  addresses:
    description: "%{address_name} is your Home address in Ontario or your most recent Ontario residence."
    address: "Address"
    street_number: House/building Number
    rural_address: "Describe where you reside"
    address_2: "Address Line 2"
    county_or_city: "County or City of residence"
    city_town: City or Town
    state: "Province"
    zip5: "Zip code"
    zip4: "Zip4"
    still_available: My Ontario residence is still available to me
    not_available: My Ontario residence is no longer available to me
    my_last_date_of_residence: "My last date of residence at the above address was:"
    unit: Unit/Suite/Apt
    direction: Street Direction

  mailing_address:
    different:
      limit: "I do not receive mail at my %{address}."
      no_limit: "I get my mail at a different address than my %{address}."

  previous_registration:
    header: "I am registered to vote at another address in Ontrario or in another Province."
    explanation: "If checked, provide the name and address below under which you are currently registered."
    update:
      no_answer: "No"
      yes_answer: "Yes"
    rural: "Check here if Rural Address or Homeless and describe where you used to reside."
    new:
      no_answer: I am not currently registered to vote in Ontario or another Province.
      yes_answer: I am currently registered to vote in Ontario or in another Province.
    address: "Address"
    address_2: "Address Line 2"
    county_or_city: "City, county, or town of residence, if applicable"
    city_town: "City/Town"
    state: "Province"
    zip5: "Zip code"
    authorize: "I authorize the cancellation or updating of my existing registration."

