fr:
  complete_section:
    title: >
      Congratulations!
      <em>Your Ontario Voter Record is almost updated.</em>
    description: >
      Don't forget, to officially update your Ontario Voter Record
      you will need to complete these steps:
    block_1: >
      <ol>
        <li>Download</li>
        <li>Print</li>
        <li>Sign</li>
        <li>Mail</li>
      </ol>
      <p>
        <strong>
          Mail your updated Ontario Voter Record to your local<br/>
          Voter Registration office:
        </strong>
      </p>
      <p>%{office_address}</p>

    block_2: >
      <p>
        Within 30 days of mailing your updated Ontario Voter Record, you should receive a<br/>
        voter card by mail that will confirm your updated Voter Record. If you do not receive a voter card<br/>
        within in that time, please contact the
        <a href="#"><strong>Ontario Board of Elections.</strong></a>
      </p>
      <p>Thank you!</p>
