en:
  confirm:
    details: Please confirm that your information is accurate. If any information is not correct, click "Edit" beside the incorrect data to return to the page to make corrections.
    voter_info: Voter Information
    required: "Yes"
    not_required: "No"
    not_provided: "Not provided"
    previous_registration:
      not_registered: "Not currently registered in Ontario or another province"
    protected_voter: '(Protected Voter)'
    absentee: '(used for absentee ballot and other voting correspondence)'

    status:
      title: Voting Status
      overseas: Overseas/Military Absentee Voter
      receiving_absentee_through: Receiving an absentee ballot for elections through
      domestic: Domestic Absentee Voter
      domestic_ballot_for: Requesting an <strong>Absentee Ballot</strong> for 
      resident: Ontario Residential Voter

    rows:
      name: Name
      eligibility: Eligibility
      voting_rights: Voting Rights
      dob: Date of Birth
      ssn: Social Security Number
      gender: Gender
      phone: Phone
      email: Email
      mailing_address: Mailing Address
      previous_registration: Previous Registration
      party_preference:
        absentee: Party preference for absentee ballots
        non_absentee: Political party preference
      protected_voter: Protected Voter
      absentee_request: Absentee Request
      assistance_request: Assistance Request
      volunteering: Volunteering

