en:
  eligibility:
    title: Eligibility
    description: Eligibility to vote in Ontario.
    update_description: "Re-confirm your eligibility and voter status"
    details: To register you must be a Canadian citizen, a resident of Ontario, and 18 years old.
    requirements:
      canadian_citizen: I am a Canadian citizen;
      aged_18: I am at least 18 years of age or older;
      on_resident: I am currently a <a href='#' data-toggle="popover" data-trigger="hover" data-title="Residence" data-content="Definition of resident TBD">resident</a> of Ontario.
    residence:
      in: I am currently a resident of Ontario.
      out: I live outside of the U.S., but the most recent U.S. residence was in Ontario.
      in_overseas: I have returned to reside in Ontario.
      out_overseas: I am still residing abroad or deployed on military duty.
    rights:
      question: Have you been convicted of a felony or been adjudicated mentally incapacitated?
      ineligible: To register, you must have had your voting rights restored.
      felony:
        question: "Have you ever been convicted of a felony?"
        state: "Province where convicted:"
        restored: "Have your voting rights been restored?"
        date: "Date when restored:"
      mental:
        question: "Have you ever been judged mentally incapacitated?"
        restored: "Has court restored you to capacity?"
    ssn:
      dont_have: "I do not have a Social Security Number"
    dmvid:
      details: By providing a valid DMV Identifier or Customer Number, you may be eligible to submit your voter registration application online, without the need to print, sign, and mail a paper application.
      dont_have: "I am not providing a Department of Motor Vehicles Identifier or Customer Number"
      unable: "If you are unable or choose not to provide DMV credentials, you may be required to print a document at the end of this process to complete your application.  Please make sure you are connected to a working printer before continuing."

