fr:
  front:
    welcome:
      title: Provincial Online Voter Registration
      text:
        You can use this online tool to register and maintain your personal information, such as name and address, on the Permanent Register of Electors for Ontario.
    steps:
      text:
        <div class='line1'>5</div>
        <div class='line2'>simple steps</div>
        <div class='line3'>to register to vote</div>
      step1: Enter information
      step2: Download
      step3: Print
      step4: Sign &amp; Date
      step5: Mail

    options:
      am_registered:
        title: "<br/>Am I on the Register"
        subtitle: Check Your Elector Record
        text: Verify and confirm your existing information on the register.
        button: Search
      add_to_register:
        title: "<br/>Add Yourself to the Register"
        subtitle: Canadian Resident Voter
        text: If you are eligible, you can add yourself to the register. <br><br>
        button: Register
      add_to_intl_register:
        title: "<br/>Add Yourself to the International Register"
        subtitle: Canadian Forces Members and Canadians Living Abroad
        text: If you are eligible, you can add yourself to the register.<br><br>
        button: Start the Online Military/Overseas Form
      update_information:
        title: "<br/>Update Your Information on the Register"
        subtitle: All Registered Ontario Voters
        text: If your personal information has changed, you can update your information.
        button: Update
      removal_from_register:
        title: <br>Remove a Deceased Elector from the Register
        subtitle: All Registered Ontario Voters
        text: If someone in your family has passed away, the elector’s name can be removed from the register.<br><br>
        button: Remove
      set_privacy:
        title: <br>Control Your Personal Information on the Register
        subtitle: ''
        text: If you do not want your personal information on the register or shared with federal or municipal election agencies, you can opt out of the register.
        button: Remove
    deadline: ""

