fr:
  search:
    no_forms:
      title: Welcome
      details:
        <p>We've created this service to help all Ontario voters -- domestic, military, and overseas --
          by providing you with access to your voter record, and information about voter registration,
          updating your record, and your options for how to vote.</p>
        <p>To get started, use the form below to check whether you are registered to vote, and to view your voter information if so.</p>
    title: Identity
    subtitle:  Please enter your personal information below. This information will be used to verify whether you are a registered elector.
    details: ''
    retry:
      You can try again by %{changing_info}, or you can %{register}.
    changing_info: changing your search information
    register: add yourself to the register

    step1: View &amp; Update
    step2: Addresses
    step3: Optional Questions
    step4: Complete

    via_ssn:
      option: Use SSN4
      first_name: Given name
      last_name: Surname (last name)
      ssn4: Last 4 digits of SSN
      dob: Date of birth
      locality: Locality

    via_vid:
      option: Use Voter ID
      voter_id: Voter ID
      dob: Date of birth
      locality: Locality

    affirmation: "I certify and affirm that the information provided to access my voter registration record is my own. I understand that it is unlawful to access the record of any other voter, punishable as computer fraud under Va. Code &sect; 18.2.152.3."
    record_not_found:
      title:  "Record Not Found"
      body:   "Based on the information provided, we cannot confirm that you are on the register."
    timeout:
      title:  "Not Available"
      body:   "Our servers are busy right now. Please try again later or contact the Board of Elections."
    record_is_confidential:
      title:  "Confidential Record"
      body:   "We are sorry, but for confidentiality reasons, the requested record cannot be displayed. To review or update your record, please contact your local general registrar or the Board of Elections."
    record_is_inactive:
      title:  "Inactive Record"

