en:
  demo_splash:
    title: Example Voter Registration Portal
    summary: "This is a demonstration of online voter registration and services capabilities. No actual voter data is used. This illustrates the freely available open source software that any state or local election official may download, modify as needed, and deploy."
    details: "This example is made possible through collaboration with the State Board of Elections, and their adaptation of this open source code.  <br/><span style='color: red'>Note:</span> The example voter records displayed are fictitious. Any likeness or similarity to any actual person is purely coincidental. No election workers were harmed in the making of this demo site."
    button_label: Enter
    footer:
      This site is brought to you by the nonprofit nonpartisan <a href="https://www.osetfoundation.org/">OSET Institute, Inc</a>. Its software is subject to the <a href="https://osetfoundation.org/public-license">OSET Public License</a>. All other content is © 2016-2021 OSET Institute, Inc. All rights reserved.
