en:
  demo_splash:
    title: Example Voter Registration Portal
    summary: "This is a demonstration of online voter registration and services capabilities. No actual voter data is used. This illustrates the freely available open source software that any state or local election official may download, modify as needed, and deploy."
    details: "This example is made possible through collaboration with the State Board of Elections, and their adaptation of this open source code.  <span style='color: red'>Note:</span> the example voter records displayed are of fictitious individuals.  Any likeness or similarity to any actual person is purely coincidental."
    button_label: Enter
    footer:
      This site is brought to you by the <a href='http://www.osetfoundation.org' target='blank'>Open Source Election Technology Foundation</a>
      and <a href='http://aws.amazon.com/' target='blank'>Amazon Web Services</a>. Its software
      content is subject to the <a href="http://www.osdv.org/legal/license" target="blank">OSET Public License</a>.
      All other content is licensed under a <a href='http://creativecommons.org/licenses/by-sa/3.0/us' target='blank'>Creative Commons Attribution-Share Alike 3.0 United States License</a>.

